services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    restart: unless-stopped
