services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ADAPTER:-node}
      args:
        - ADAPTER=${ADAPTER}
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./build
        target: /app/static
    ports:
      - '${PORT}:${PORT}'
